### ISSUE TITLE
No panels configured error

### ISSUE THREAD

**Issue by Analect** [SuchMonkey/qbert#1]
Hi. Came across your repo ... and wanted to see what it did.
Can you point me towards how/where I add a panel configuration?

```
> @ start /home/mccoole/Development/Tools/Polymer/qbert
> node makefile.js build && electron ./dist/main.js --enable-transparent-visuals

Clean ./dist/
Transpile [js] to ./dist/
-> babel: 0
    src/main.js -> dist/main.js
    src/panelFactory.js -> dist/panelFactory.js
    src/renderer/app.js -> dist/renderer/app.js
No panels configured!
```

**Comment by SuchMonkey** [comment]
Hi, 

the configuration to look for panels is as follows:

%USERHOME%/.config/qbert
%USERHOME%/.qbert
%USERHOME%/qbert

%USERHOME% resolves on Linux to /home/USERNAME
and on Windows to C:/users/USERNAME

Furthermore you can find some example panels here:

[https://github.com/SuchMonkey/qbert/tree/master/doc/examples/panel-config-structure](https://github.com/SuchMonkey/qbert/tree/master/doc/examples/panel-config-structure)

Just place the panels directory in one of the described config locations.
